// This file has been autogenerated using CoD4X 1.8 server. //
// If it contains wrong data, please create issue here:     //
//    https://github.com/callofduty4x/CoD4x_Server/issues   //
// Correct issue with maps that reference old CJ Functions.

loadPos()
{
	self thread [[level._cj_load]](1);
}

savePos()
{
	self thread [[level._cj_save]](1);
}